builds:
  - goos:
      - windows
      - darwin
      - linux
    env:
      - CGO_ENABLED=0

dockers:
  - image_templates:
      - "dshaburov/ebs-snapshot-exporter:latest"
      - "dshaburov/ebs-snapshot-exporter:{{ .Tag }}"
    extra_files:
      - config.yaml
